### ISSUE TITLE
Option debug to false doesn't seem to be working

### ISSUE THREAD

**Issue by m-frachet** [thomseddon/node-oauth2-server#128]
I actually need to display only the first line of the error like : "OAuth2Error: The access token was not found"

Actually, using debug false in the options doesn't seem to work properly and continues to display the full stack error

**Comment by hbomb9000** [comment]
I am seeing this same thing. I've gone through it and am certain that it's displaying the error in the console without going through the function defined at this.debug.

I am testing this by providing an invalid accesstoken to a request which requires authorization. Additionally, no response is returned, so the request remains open until it times out. It is unclear as to where the error is being output to the console, but I am investigating further.

**Comment by hbomb9000** [comment]
Server example: 
```
  oAuthModel.init()
  app.oauth = oauthServer
    model: oAuthModel
    grants: ['client_credentials']
    debug: false

  app.use(app.oauth.errorHandler())

  app.all '/oauth/token', urlEncodedParser, app.oauth.grant()

  app.get('/secret', urlEncodedParser, app.oauth.authorise(), (req, res) ->
    console.log "SECRET AREA FOUND!!!"
    # This is a test route for oAuth
    res.send('Secret Area');
  )
```

It's when I call /secret where I get the problem.

**Comment by thomseddon** [comment]
The error handler is just another middleware, it must therefore be inserted **after** your routes, so your example becomes:

```coffee
 oAuthModel.init()
  app.oauth = oauthServer
    model: oAuthModel
    grants: ['client_credentials']
    debug: false

  app.all '/oauth/token', urlEncodedParser, app.oauth.grant()

  app.get('/secret', urlEncodedParser, app.oauth.authorise(), (req, res) ->
    console.log "SECRET AREA FOUND!!!"
    # This is a test route for oAuth
    res.send('Secret Area');
  )
 
 app.use(app.oauth.errorHandler())
```

**Comment by thomseddon** [comment]
Closing as I think we have solution, please reopen if still not working
