### ISSUE TITLE
Is there example that uses JWT?

### ISSUE THREAD

**Issue by memelet** [thomseddon/node-oauth2-server#130]
I assume that to use JWT all that is required is to implement generateToken using JWT. Is this correct? Does anybody know of an example?

**Comment by memelet** [comment]
Sure, go ahead and close. My spike with jwt is going well. Its in the context of a larger system, but I will factor out an example once its stable.

**Comment by thomseddon** [comment]
Thanks

**Comment by jeromyevans** [comment]
I've shared an example using JWT based on the in-memory model:
https://github.com/jeromyevans/node-oauth2-jwt-example
If you'd like the example as a PR I'm happy to create one.

**Comment by igorescobar** [comment]
Would be very nice to have something like that implemented. :+1:
