### ISSUE TITLE
`model.extendedGrant` cannot verify client_id

### ISSUE THREAD

**Issue by natevw** [thomseddon/node-oauth2-server#139]
The other grant types make sure that the client id from the authorization header matches the provided client_id parameter. However, if the extendedGrant handler wants to base its actions off of the actually verifed clientId, there's no clear way for it to do so — it can only access the *supposed* client_id passed in the body, which may be spoofed!

Either the authorized client id should be passed to the helper, although that would be an incompatible change. Perhaps if the user object *returned from* the `extendedGrant` delegate method includes a `clientId` field, it would be compared to `self.client.clientId` as done in the `useAuthCodeGrant` logic? So at least `extendedGrant` could opt-in to a followup check.

**Comment by thomseddon** [comment]
Ah, I understand, makes sense - we recently fixed a similar issue by adding the verified client credentials into the `req` object (https://github.com/thomseddon/node-oauth2-server/blob/master/lib/grant.js#L354-L357), perhaps if we just moved this assignment further up, inside the `checkClientCredentials` function?

**Comment by thomseddon** [comment]
Comments welcome on #143

**Comment by natevw** [comment]
This should work nicely, thanks for the quick improvement!
