### ISSUE TITLE
Extension grant should be any valid URI

### ISSUE THREAD

**Issue by phw** [thomseddon/node-oauth2-server#140]
According to the spec the extension grant can be any valid URI. Currently node-oauth2-server expects it to start with either `http://` or `https://`, but any other URI should also work. E.g. if one wants to implement the JWT Bearer Token Grant Type the grant_type URI for the authorization grant is `urn:ietf:params:oauth:grant-type:jwt-bearer`.

See
https://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer-12#section-2.1
http://tools.ietf.org/html/rfc6749#section-4.5

A library that seems to handle the validation of URIs is https://github.com/garycourt/uri-js , but I have never used it.

**Comment by thomseddon** [comment]
Very good point, I have thought about this before but never looked into it much.

Rereading the rfc I think there is a case for just accepting any string as an extension grant?

@ruimarinho @mjsalinger @alex-whitney ?

**Comment by phw** [comment]
Yes, I think that would make sense, thus passing every grant that is not known to the extension grant handler.

I will probably do a generic implementation for the JWT Bearer Token grant type which can easily be hooked into node-oauth2-server. Would you actually be interested into adding this directly to node-oauth2-server?

**Comment by mjsalinger** [comment]
The spec does specify a URI, but the example they give follows the urn scheme.  It's worth noting that all of the proposed extension grant standards (Oauth-Saml2, JWT, and MAC) use the URN format.  So I think validating that it is either a valid URI or a valid URN would be the fine here, but I'd see nothing wrong with opening it up to any string, as it has to be properly interpreted by the server anyways and match whatever scheme is defined.

**Comment by phw** [comment]
@mjsalinger A URN *is* a valid URI, it is actually a more specific URI.

**Comment by thomseddon** [comment]
How about #142

**Comment by thomseddon** [comment]
#142 Merged
