### ISSUE TITLE
Revocation tests

### ISSUE THREAD

**Issue by emanuelef** [thomseddon/node-oauth2-server#141]
Hi,
I couldn't find tests about revocation, is it something supported ?

My use case is: a third party client app registers and gets clientId/ClientSecret, then uses Client Credentials flow to get Access Token and then perform APIs calls on the Resource Server.
I then decide to revoke the access to my APIs to that particular client App, if the Authorization server doesn't revoke the Access Token (and even the Refresh one) the client can keep performing secured APIs calls.

How can I revoke the access and refresh token? Is there an example ?

Thanks a lot in advance

**Comment by thomseddon** [comment]
You authorise every client in [`getClient`](https://github.com/thomseddon/node-oauth2-server#getclient-clientid-clientsecret-callback), you could check if the client is revoked here and if so not return any client details - this would result in an `invalid_client` "Client credentials are invalid" error

Another option would be to implement [`grantTypeAllowed`](https://github.com/thomseddon/node-oauth2-server#granttypeallowed-clientid-granttype-callback) and return `invalid_client` "The grant type is unauthorised for this client_id"

I'm not aware of anything in the spec specifically about revocation

**Comment by emanuelef** [comment]
Thanks

**Comment by emanuelef** [comment]
Sorry one last question, getClient seems to be called during the OAuth flow but not when accessing the secured API.
How can I check there that the Access Token used is not from a Client that was revoked ?
I've overridden requireUser, how can I retrieve the clientId from the the Access Token?
Thanks

**Comment by thomseddon** [comment]
In your [`getAccessToken`](https://github.com/thomseddon/node-oauth2-server#getaccesstoken-bearertoken-callback) when you pull out the access token you can check the associated client id is still valid

**Comment by emanuelef** [comment]
Thanks, I'll try that.
How do I get clientId from the bearer token ?

**Comment by thomseddon** [comment]
You should be storing it alongside the token, this is how it's done in the examples: https://github.com/thomseddon/node-oauth2-server/blob/master/examples/postgresql/model.js
