### ISSUE TITLE
Deprecated method causing errors

### ISSUE THREAD

**Issue by morious** [thomseddon/node-oauth2-server#153]
express deprecated res.send(status, body): Use res.status(status).send(body) instead at node_modules\oauth2-server\lib\oauth2server.js:130:9

**Comment by alexnj** [comment]
I see that it's been fixed in a commit right before 2.3.0, but 2.3.0 hasn't included that fix. @thomseddon, when is 2.3.1?

**Comment by DeathTroll** [comment]
+1

**Comment by maxnachlinger** [comment]
No need to be blocked, just do this in your package.json
```json
"dependencies": {
  "oauth2-server": "git://github.com/thomseddon/node-oauth2-server.git"
}
```
You can also specify the commit if you'd rather not use the HEAD.

**Comment by thomseddon** [comment]
Sorry about this, it's my fault as there was one more change I wanted to bundle into 2.4.0 which I haven't finished!

**Comment by thomseddon** [comment]
2.4.0 released, sorry about delay
