### ISSUE TITLE
Returned client and user object not updated to request object.

### ISSUE THREAD

**Issue by sobenz** [thomseddon/node-oauth2-server#156]
The documentation for the model states that the client and user objects that are returned from *getClient* and *getUser* respectively will be stored in the request object. This however does not appear to be the case as they are not accessible when coming to the *generateToken* method. Looking at the code it would appear they are being saved at the parent object rather than in the request object.

**Comment by thomseddon** [comment]
This may have be fixed on master: https://github.com/thomseddon/node-oauth2-server/commit/0050abfb124b78c382b7bead8b184b8a16644768

**Comment by sobenz** [comment]
right you are :)

**Comment by thomseddon** [comment]
Thanks, sorry it hasn't been released yet!
