### ISSUE TITLE
Proposal to change the Apache license to MIT

### ISSUE THREAD

**Issue by nunofgs** [thomseddon/node-oauth2-server#159]
Hi @thomseddon,

What do you think of  changing the license of this project from *Apache* to *MIT*?

The *Apache* license requires the license header to be included in every source file which takes up at least 15 lines at the beginning of each file.

There are also many projects that have changed from *Apache* to *MIT* due to its incompatibility with the *GPL* license.

It seems to me that the major difference between these licenses is the added patent grant that *Apache* provides. Are you at all concerned about possible patent issues?

**Comment by thomseddon** [comment]
I'd be up for it, I started this a while ago and since then almost all projects I've done use MIT, happy to do this in 3.0.0

**Comment by nunofgs** [comment]
Great :)

That brings me to a related question:

We at [Seegno](https://github.com/seegno) feel that this project has enough reputation and responsibility in the community that it is worth moving to its own organization. What do you think?

**Comment by thomseddon** [comment]
Interesting idea, few questions:

- what difference do you think this would make / what is the main goal?
- how would it work?

I guess my immediate thought would be that this is nowhere near the popularity of some projects that don't have an organisation?

**Comment by nunofgs** [comment]
We feel that this project is the *de-facto* standard for implementing an *OAuth2* server in node.

In our opinion, migrating to an *OAuth* organization (for example: *oauth.js/oauth2-server*) would:

1. Give the project a more serious tone.
2. Encourage developers to contribute other *OAuth*-related projects (such as our [seegno/angular-oauth2](https://github.com/seegno/angular-oauth2) project which we would be happy to move as well)
3. We could time this with the release of 3.0.0 and introduce a more modern ES6 implementation, using [Babel](https://github.com/babel/babel) (we would contribute this PR, of course).

/cc @ruimarinho, @fixe

**Comment by thomseddon** [comment]
Welcome comments from anyone else on this

/cc @mjsalinger @alex-whitney

**Comment by ruimarinho** [comment]
I agree on both points - moving to the MIT license will foster even more contributions and creating an organization for OAuth related work can be greatly beneficial to the node ecosystem and increase awareness both in terms of compliance and security.

**Comment by fixe** [comment]
I agree completely with @nunofgs.

**Comment by mjsalinger** [comment]
This was done in PR #203
