### ISSUE TITLE
State of this module

### ISSUE THREAD

**Issue by marcosbergamo** [thomseddon/node-oauth2-server#161]
Hello everybody!

I see a lot of issues and PR on this module, but, nobody accept the PR, is an active module? Updates are coming?

**Comment by lfk** [comment]
Hi there. Absolutely, the project's alive and well. There's plenty of work in progress, targeting the [3.0.0 release milestone](https://github.com/thomseddon/node-oauth2-server/issues?q=milestone%3A3.0.0).

**Comment by thomseddon** [comment]
Alive and well but short on time like everyone else :)

All outstanding PR's either require more work or are awaiting input from me...

**Comment by marcosbergamo** [comment]
Yeah, I see a lot of PR and Issues opened and I feeling a little fear on use. But thanks for yours replies =D

If I can help in anyone I will !
