### ISSUE TITLE
Unclear documentaion

### ISSUE THREAD

**Issue by jwerre** [thomseddon/node-oauth2-server#164]
Under [https://github.com/thomseddon/node-oauth2-server#features](Features) you say you support: `authorization_code`, `password`, `refresh_token`, `client_credentials` and `extension` grant types.

Under [https://github.com/thomseddon/node-oauth2-server#options](Options) you say: currently the module supports `password` and `refresh_token`

Just thought you would want to know

**Comment by thomseddon** [comment]
This has been fixed since
