### ISSUE TITLE
Trouble adding client id to header

### ISSUE THREAD

**Issue by jwerre** [thomseddon/node-oauth2-server#167]
If I add the `client_id` and `client_secret` to the form data it seems to work fine

    curl http://localhost:3000/oauth/token 
        --request POST
        --data "grant_type=password&username=me&password=123456&client_id=123&client_secret=abc"
        --header "Content-Type: application/x-www-form-urlencoded"

response:

    {
        "token_type":"bearer",
         "access_token":"d10a5aa6a66c656998041eb03f2c57ce9f1db63a",
        "expires_in":3600,
        "refresh_token":"1f5016fef9c4903b33efe7136c43c03b2626401a"
    }

However when I try to base64 encode it and add it to the header:

    echo "123:abc" | openssl enc -base64
    MTIzOmFiYwo=

    curl http://localhost:3000/oauth/token
        --request POST
        --data  "grant_type=password&username=me&password=123456"
        --header "Content-Type: application/x-www-form-urlencoded"
        --header "Authorization: Basic MTIzOmFiYwo="

... I get an `invalid_client` error: 

    {
        "code":400,
        "error":"invalid_client",
        "error_description":"Invalid or missing client_id parameter"
    }

What am I missing?

**Comment by mjmasn** [comment]
@jwerre I've been having a similar issue. I tried ```Authorization: Basic MTIzOmFiYwo=``` which worked (I assume you just threw some dummy values in, unless you have a different issue). Eventually worked out it's something like if the client_id exceeds 40 characters the error is thrown. I don't think the oauth 2 spec sets a limit so this may be a bug...

**Comment by mjmasn** [comment]
It looks like this is deliberate but configurable in the options. From the README:

- *regexp* **clientIdRegex**
 - Regex to sanity check client id against before checking model. Note: the default just matches common `client_id` structures, change as needed 
  - Default: `/^[a-z0-9-_]{3,40}$/i`

**Comment by jwerre** [comment]
Cool, I'll check that out. Thanks @mjmasn

**Comment by thomseddon** [comment]
Yes sorry this has been a stumbling block before - I think this should restriction should be removed for 3.0.0 - tracking in #178
