### ISSUE TITLE
Sqlite - Curious in an example adapter?

### ISSUE THREAD

**Issue by four43** [thomseddon/node-oauth2-server#168]
Hello all,

I'm making a sqlite adapter for a project. Would you guys be interested in using it as an example adapter? I can toss it in a pull request if you're interested. We chose sqlite because it's small, simple, easy, and good for random little projects, hopefully we can help out others.

Interested?

**Comment by thomseddon** [comment]
Yeah the more the merrier!

**Comment by thomseddon** [comment]
Closing awaiting a PR

**Comment by four43** [comment]
I totally forgot about this sorry. I'll see if I can get something together.
