### ISSUE TITLE
error as json response

### ISSUE THREAD

**Issue by ChrisTerBeke** [thomseddon/node-oauth2-server#172]
I'm building a JSON rest api, and I can't seem to get any OAuth2Error object as json response (they are printed as normal error on screen and in my console). I'd really like a way to customise the way that the package returns errors as express response.

**Comment by ChrisTerBeke** [comment]
Found the problem. You have to call the app.use(APP.app.oauth.errorHandler()) AFTER you added all your routes to the application, otherwise, there is no next() function available.

**Comment by lvsl** [comment]
Actually I would like to Winston library for logging all errors. But no idea how to do this

**Comment by ChrisTerBeke** [comment]
I guess you could call next when an error occurs and then write your own middleware that passes it to a Winston instance?

**Comment by lvsl** [comment]
Maybe I misunderstood how error handling work with the next() callback, but I did the following hack to make it work:

https://gist.github.com/lvsl/1868e9db2b41dc8f96e7

**Comment by thomseddon** [comment]
@lvsl Where is the error passed to winston in that gist, it seem to just replicate the `errorHandler` middleware?

As @ChrisTerBeke suggests, you could catch the errors by having something like this before `errorHandler`:

```js

app.use(function (err, req, res, next) {
  logger.log('info', err); // pass to winston
  next(err); // pass on to 
});

app.use(app.oauth.errorHandler()); // Send back oauth compliant response
```

If you really wanted to only handle OAuth errors you could do the following:

```js

var OAuthError = require('oauth2-server/lib/error');

app.use(function (err, req, res, next) {
  if (err instanceof OAuthError)
    logger.log('info', err); // pass only oauth errors to winston
  next(err); // pass on to 
});

app.use(app.oauth.errorHandler()); // Send back oauth compliant response
```

**Comment by thomseddon** [comment]
(closing as original query solved)
