### ISSUE TITLE
When the access_token expired in getAccessToken

### ISSUE THREAD

**Issue by arthurtalkgoal** [thomseddon/node-oauth2-server#173]
Hi, 
I wonder whether the ```getAccessToken``` is correct as written in ```examples/mongodb/model.js``` ( ***password and refresh_token*** grand type)

The function is simple as:
```
model.getAccessToken = function (bearerToken, callback) {
  console.log('in getAccessToken (bearerToken: ' + bearerToken + ')');

  OAuthAccessTokensModel.findOne({ accessToken: bearerToken }, callback);
};

```
and there is not expiration checking. How the grant_type access_token got expired?

**Comment by lvsl** [comment]
I think that expiration happens after this method.
As per documentation, the callback should have an 'expires' field, so this is used to check for expiration I think.

My getAccessToken looks like this:

    getAccessToken: function getAccessToken(bearerToken, callback) {
    db.AccessToken.findOne({ 'accessToken': bearerToken }, function foundAccessToken(err, token) {
      if (err || !token) {
        return callback(err);
      }
      db.User.findOne({ 'email': token.userId }, '-_id -__v', function loadUser(err, user) {
        if (err || !user) {
          return callback(err);
        }
        callback(null, { accessToken: token.accessToken, clientId: token.clientId, expires: token.expiresAt, user: user, userId: token.userId });
      });
    });
  },

**Comment by thomseddon** [comment]
Expiration is checked within the module it's self, you should include an `expires` key as @lvsl mentions, this will be compared against the servers current time to establish if the token has expired - if it has it will send back the correct response.

Here's the relevant code for authorisation flows: https://github.com/thomseddon/node-oauth2-server/blob/master/lib/authorise.js#L110-L122

**Comment by arthurtalkgoal** [comment]
Hi @thomseddon  and @lvsl 

Thanks for the explanation! That solved my puzzles.  

Since I copied the codes somewhere in the examples, the access token is simple accessing the database/mongo:

```
//
// oauth2-server callbacks
//
model.getAccessToken = function (bearerToken, callback) {
  console.log('in getAccessToken (bearerToken: ' + bearerToken + ')');
  OAuthAccessTokensModel.findOne({ accessToken: bearerToken }, callback);
};
```

That hide the ```expires``` fields codes or simply missing. 

Let me update my codes, thanks again.
