### ISSUE TITLE
How to get a user-related from token in a request?

### ISSUE THREAD

**Issue by mraffo** [thomseddon/node-oauth2-server#179]
//POST - Insert a new Party in the DB
exports.addParty = function(req, res) {
	console.log('PartyController: POST');
	console.log(req.body);
        ..
}

I need the user from recieved token in the request to create a party entity.

Thanks!

**Comment by OllieJennings** [comment]
If l am right, the user will be in the `req.user` object, as long as the route requires the user to be oauthed at that point.

**Comment by mraffo** [comment]
Yes! thanks!
