### ISSUE TITLE
How to validate if authenticated user has permission to show some info?

### ISSUE THREAD

**Issue by mraffo** [thomseddon/node-oauth2-server#180]
For example:

I have this route:
router.route('/api/users/:id/parties').get(app.oauth.authorise(), partyController.findByOwner);

Ok, if we soppouse param.id equals to req.user.id we dont do anything, but, when the param.id and the user.id of authenticated user does not match the authenticated user must not show the info of another user.

So, how is the best way to validate this things when we make a REST apis.

Thanks!

**Comment by mraffo** [comment]
Anything?

**Comment by thomseddon** [comment]
Sorry I don't follow - what are you trying to achieve?
