### ISSUE TITLE
Refresh Token Grant Type Issuing a New Refresh Token

### ISSUE THREAD

**Issue by jvitorsf** [thomseddon/node-oauth2-server#184]
Hey, guys. I'm having a problem when I try to issue an access token using the refresh token grant type. It retrieves an access token and also a new refresh token.

If I'm correct it should return only the new access token and not a new refresh token.
Am I missing something?

Thanks in advance.

**Comment by thomseddon** [comment]
Yeah that's the intended behaviour, from the spec:

>  The authorization server MAY issue a new refresh token, in which case
   the client MUST discard the old refresh token and replace it with the
   new refresh token.  The authorization server MAY revoke the old
   refresh token after issuing a new refresh token to the client.  If a
   new refresh token is issued, the refresh token scope MUST be
   identical to that of the refresh token included by the client in the
   request.

https://tools.ietf.org/html/rfc6749#section-6

**Comment by jvitorsf** [comment]
Awesome! Thank you!
