### ISSUE TITLE
Offering the Chance to define: Extension grant type

### ISSUE THREAD

**Issue by fabianfett** [thomseddon/node-oauth2-server#188]
Hi,

I think it would be great, if one could implement his/her own extension grant type. Use cases could be AppStore receipts (for the different App Platforms).

I am certainly not a OAuth2 pro, but as far as I can see this is something that can be achieved with the OAuth2.0 Framework, See: 4.5. Extension Grants: https://tools.ietf.org/html/rfc6749#section-4.5 

Thanks for your time and consideration.

PS.: I am quite new to node but I would love to help to create a PR, if someone is interested. I might need coaching on style and common pitfalls though ;-)

**Comment by fabianfett** [comment]
I am so blind! Looking into the code I found what I was looking for.

function useExtendedGrant (done)

Perfect. Sorry, for the inconvenience!

**Comment by thomseddon** [comment]
:)
