### ISSUE TITLE
Error Console Logging even with debug: false

### ISSUE THREAD

**Issue by fb13** [thomseddon/node-oauth2-server#192]
Hi,

I have the following oauth2-server options:

```javascript
app.oauth = oauthserver({
	model: oauth,
	grants: ["password"],
	debug: false
});
```

When I access POST /oauth/token with some random data OAuth2Error are being thrown. In some of my test cases I provoke such a behavior and test whether my application behaves correctly by discarding the random input and delivers a nice json response with some error description.

__Problems:__

1. Every time an error occurs it is printed into the console and thereby makes the whole test report look like a giant error log. As you can see I already set debug to false.
2. All errors result in 500 Internal Server Error although it often is just a parameter the user forgot. Wouldn't Bad Request in such cases makes more sense? I could not find an option to change the response message including the http error code.

**Comment by thomseddon** [comment]
Hi, using the minimal example in the readme but changing debug to false: https://gist.github.com/thomseddon/66d95e2e2658b0911ca9

I don't get any output - could you post a complete but minimal example?

**Comment by fb13** [comment]
Hi,

Here is a small example with an example request and a console output: https://gist.github.com/fb13/68025026aaf9235a88fd

**Comment by fb13** [comment]
Nobody knows?

**Comment by carebdayrvis** [comment]
I too am having this problem.

**Comment by thomseddon** [comment]
This is because your errorHandler is included before your routes, so it doesn't catch the errors, see how in my example & in the readme it's after: https://gist.github.com/thomseddon/66d95e2e2658b0911ca9#file-test-js-L23

Sorry for the delay in getting back to you - please re-open if that doesn't fix it!
