### ISSUE TITLE
Question: Is it possible to use the password grant type without passing the client secret?

### ISSUE THREAD

**Issue by bloudermilk** [thomseddon/node-oauth2-server#198]
I'm considering using this module to secure an iOS app API. The app is trusted so we're interested in using the "password" grant type so that we can avid using a webpage and redirects. It looks like this module supports the grant type but it requires the client secret, which for obvious reasons we can't store safely in the app. Does this module support this or is there another recommended method? I'm currently passing in an arbitrary value for the client secret and ignoring it in `getClient`.

**Comment by thomseddon** [comment]
You can use the password grant type but you should be prepared for the fact that if someone finds your secret (or find you're ignoring it) they can generate tokens themselves with correct credentials.

My approach here has been to use a secret with a view to rotating it if there ever was observed misuse, I'd be interested to know how others approach this

**Comment by bloudermilk** [comment]
Thanks for the tips. We do intend to use the client secret for other trusted endpoints so unfortunately we won't be able to go with the rotation strategy you mentioned. For now we'll continue to pass a placeholder secret and ignore it, unless you have any other ideas :)

**Comment by thomseddon** [comment]
The rotation should still work, you can create a client/secret pair and put these in your application then as time goes on you may generate a new pair, then when ready you can disable the original pair. The idea is you just treat your self as another (perhaps more privileged) API client
