### ISSUE TITLE
Add some examples.

### ISSUE THREAD

**Issue by manjeshpv** [thomseddon/node-oauth2-server#201]
Please provide some request/response patterns of whole oauth workflow

As per the specification of OAuth 2.0(as i understand),

![oauth_web_server_flow](https://cloud.githubusercontent.com/assets/1999957/8692423/c3843b66-2aeb-11e5-9342-03c5ae53cd57.png)

Can anyone post all request/response patterns

1. Browser:  *POST /oauth/authorize?client_id,username,password* 
2. Browser will get authorization code like *88ea5c85d*
3. Browser: *GET http://oauth-client.com/gotAuthorization?auth_code =88ea5c85d*
4. Now OAuth client will get auth_code
5. OAuth Client:   *POST /oauth/token?client_id,client_secret,authorization code* 
6. OAuth Server: returns access_token like fe0333f6c620577de1822eef9c70e05702aa0c91
7. OAuth Client: will get access_token and get resources using *POST /data/ Authorization: Bearer fe0333f6c620577de1822eef9c70e05702aa0c91(here I confused, browser will use Authorization: Bearer or oauth client)

Please help me to understand the flow.

**Comment by thomseddon** [comment]
Hi,

This module probably isn't the best way to learn about OAuth in general, for examples of how to use this module specifically then please check in here: https://github.com/thomseddon/node-oauth2-server/tree/master/examples
