### ISSUE TITLE
client_credentials should not require a user

### ISSUE THREAD

**Issue by romainfrancez** [thomseddon/node-oauth2-server#202]
Per rfc https://tools.ietf.org/html/rfc6749#section-1.3.4
"Client credentials are used as an authorization grant typically when the client is acting on its own behalf"

I can fix it if you'd like.

**Comment by kittrCZ** [comment]
is there any update on this issue? I would like to use the client_credentials flow for server-to-server communication.

**Comment by romainfrancez** [comment]
I wish but I haven't heard from the repo maintener

**Comment by kittrCZ** [comment]
@thomseddon do you have updates on this?

**Comment by frapontillo** [comment]
As of now, the user is not required for the `client_credentials` grant type, but it is required for the `refresh_token` one, that will eventually be used to fetch a new access token with the provided refresh token.
@thomseddon, I think this can be easily fixed, should we open a PR?

**Comment by romainfrancez** [comment]
Yes, that's an easy fix however, we have no answer from the repo owner :s

**Comment by charleston10** [comment]
See here https://github.com/thomseddon/node-oauth2-server/issues/217

**Comment by thomseddon** [comment]
Happy to review a PR! :)
