### ISSUE TITLE
Redirect_uri should be required, if the "redirect_uri" param was included in the authorization request

### ISSUE THREAD

**Issue by visvk** [thomseddon/node-oauth2-server#204]
In `authorization_code` grant, redirect_uri is required, if the "redirect_uri" param was used in the authorization request.
From https://tools.ietf.org/html/rfc6749#section-4.1.3

```
redirect_uri is required,if the "redirect_uri" parameter was included in the
authorization request as described in Section 4.1.1, and their values MUST be identical.
```

**Comment by thomseddon** [comment]
I think this is how the grant currently works: https://github.com/thomseddon/node-oauth2-server/blob/master/lib/authCodeGrant.js#L92-L96 ?

Closing as it's taken me so long to reply, please feel free to re-open if needed :)
