### ISSUE TITLE
Custom the response from the server?

### ISSUE THREAD

**Issue by khanghoang** [thomseddon/node-oauth2-server#205]
Hi guys,

I ran into a problem that I wanna custom the returned json instead of the default one. Is there anyway to do that?

**Comment by charleston10** [comment]
the specification Oauth2 follows a pattern, if you change, then do not use.

**Comment by thomseddon** [comment]
It's currently unsupported but we've looked at this before in #115 

I'll close this but please reopen if that doesn't quite work for you!
