### ISSUE TITLE
Insufficient Error Handling in usePasswordGrant(done)

### ISSUE THREAD

**Issue by roschumacher** [thomseddon/node-oauth2-server#206]
In grant.js within the usePasswordGrant Method you do
```
return this.model.getUser(uname, pword, function (err, user) {
    if (err) return done(error('server_error', false, err));
```
That means, independently of `err` a server_error is returned. Here for example should be checked, if `err` is of type `OAuth2Error` in order to handle the error respectively.

Why do i have this problem: In my implementation of the `authenticate` method, i check if the user trying to log in has already confirmed his email address. If not, i pass an respective error. Unfortunately, the error get's not returned by the server because of the problem stated above.

In general, can I somehow extend the error types specified in error.js?

**Comment by thomseddon** [comment]
This is a valid request - it would be good to be able to extend the module and throw your own errors, this isn't something that's currently supported.

This has been propsoed in #115 - I'm going to close and we can track in there?

Please reopen if that doesn't hit the spot!
