### ISSUE TITLE
node-oauth2-server to authenticate with thridparty services

### ISSUE THREAD

**Issue by szafarcin** [thomseddon/node-oauth2-server#207]
Hi,
I have gone through the initial doc of node-oauth2-server, need to clarify couple of things:

1) node-oauth2-server server seems to provide a new-service holder to provide oauth2 service so that they can login to that services using the methods supported.

2) Is it possible to use this server to integrate with third-party services e.g.Google, Facebook etc?  making this oauth server as a single sign-on to all the thrid-party services?

Looking forward to your valuable reply. 

Regards
SZ

**Comment by thomseddon** [comment]
Hi,

This module is aimed towards those who want to build their own OAuth server for their users to authenticate against. You can create your own grant types (https://github.com/thomseddon/node-oauth2-server#extension-grants) which could involve the user being sent to facebook to authenticate.

I'll close this for now but please feel free to re-open if you have follow up questions

Thanks!
