### ISSUE TITLE
Optional for returning a different id

### ISSUE THREAD

**Issue by Downstairz** [thomseddon/node-oauth2-server#210]
Is there a way for me to define my own User's table?

Instead of a "User" table I have an "Account" table for my Users.

So on line 126 in authorise.js, it's returning "userId"

I would like to return an "AccountId"

self.req.user = token.user ? token.user : { id: token.AccountId };

instead of "useId"

self.req.user = token.user ? token.user : { id: token.userId };

Is there a setting where I can override the define "User" table definition and come up with my own key?  I could go about it different by just defining my user key with "userId" as my foreign key.  Not a big deal. 

Thanks,

Buddha

**Comment by thomseddon** [comment]
Yes!

You can return an object in place of "user" and this will be loaded into `self.req.user`, you could even wrap the authorise function to save this value in `req.account` if that is more useful
