### ISSUE TITLE
Validating Access Tokens

### ISSUE THREAD

**Issue by vish-k** [thomseddon/node-oauth2-server#211]
Hello,
Thanks for creating this module. Can you pls address following questions - 
1. I was able to try out authorization code grant functionality till the point of client obtaining tokens. However, I didn't find any reference for resource server to validate the access tokens. Are there any samples/documents that describe this functionality ?
2. Does the module provide any APIs for managing grants/clients/tokens ? Or are we supposed to implement if based on the (storage) model selected ?
3. Are there any full fledged/production ready (with API/scalability etc) implementation available ? 

Thanks again for your time and efforts.

**Comment by charleston10** [comment]
I started a project where I need to use authentication token.
Used this lib and solved most of my problems, I had to change some things in relation to refresh_token, but nothing very significant.
Is working very well, the job you have will be to create the life cycle in its front-end application.

-  {1}  (in file oauth2-server/lib/grant.js)
See more http://oauth.net/documentation/
- {2} both
- {3} this application can be used in production, just need to be careful to create your server securely

**Comment by vish-k** [comment]
Thanks for the reply. I have some follow up questions -
1. I looked at grant.js file but still could not find any functions to validate the tokens. By validate token, I am referring to interaction between resource server and auth server similar to following 
        - https://developers.google.com/identity/protocols/OAuth2UserAgent#validatetoken
        - https://documentation.pingidentity.com/display/PF73/Grant+Type+Parameters#GrantTypeParameters-1079271

2. Is there any documentation for existing API for managing grants/client/token ? I didn't find any references.

**Comment by thomseddon** [comment]
Hi,

The main documentation is in the Readme: https://github.com/thomseddon/node-oauth2-server

But the best way to get started would be to checkout the examples: https://github.com/thomseddon/node-oauth2-server/tree/master/examples

With regards to your specific questions, you can check tokens that have been created via the getAccessToken function: https://github.com/thomseddon/node-oauth2-server#getaccesstoken-bearertoken-callback

This is called whenever a token is used and you can hook any logic into there. You may also find the grantTypeAllowed function useful: https://github.com/thomseddon/node-oauth2-server#granttypeallowed-clientid-granttype-callback

Please feel free to re-open if there's anything else we can help with!
