### ISSUE TITLE
TypeError: this.model.getClient is not a function

### ISSUE THREAD

**Issue by ArielSaldana** [thomseddon/node-oauth2-server#214]
I'm getting the error : 

TypeError: this.model.getClient is not a function<br> &nbsp; &nbsp;at Grant.checkClient (/home/projects/oauth-server/node_modules/oauth2-server/lib/grant.js:136:14)<br> &nbsp; &nbsp;at run (/home/projects/oauth-server/node_modules/oauth2-server/lib/runner.js:15:14)<br> &nbsp; &nbsp;at /home/projects/oauth-server/node_modules/oauth2-server/lib/runner.js:17:7<br> &nbsp; &nbsp;at Grant.extractCredentials (/home/projects/oauth-server/node_modules/oauth2-server/lib/grant.js:92:3)<br> &nbsp; &nbsp;at run (/home/projects/oauth-server/node_modules/oauth2-server/lib/runner.js:15:14)<br> &nbsp; &nbsp;at runner (/home/projects/oauth-server/node_modules/oauth2-server/lib/runner.js:19:5)<br> &nbsp; &nbsp;at new Grant (/home/projects/oauth-server/node_modules/oauth2-server/lib/grant.js:57:3)<br> &nbsp; &nbsp;at /home/projects/oauth-server/node_modules/oauth2-server/lib/oauth2server.js:88:5<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/projects/oauth-server/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/projects/oauth-server/node_modules/express/lib/router/route.js:131:13)

Any fix for this

**Comment by moravcik** [comment]
I have same problem here, do you have any resolution for this?

**Comment by deveshsinghal22** [comment]
Hi @ArielSaldana ,

I am also getting same error. can you please tell me, how did you fix? 
I am surely missing something. I used basicAuth in postman and passing below params
grant_type:password
client_id:57d948523066970534cdc8e3

**Comment by maxtruxa** [comment]
Hi @deveshsinghal22, are you using the stable version from npm or are you using master?

**Comment by deveshsinghal22** [comment]
i am using latest version

**Comment by maxtruxa** [comment]
That didn't really answer my question.. Which is the exact version shown in the `package.json`?

**Comment by deveshsinghal22** [comment]
`"oauth2-server": "^2.4.1",`

**Comment by maxtruxa** [comment]
Did you implement `getClient` on your model? It's described in the [readme](https://www.npmjs.com/package/oauth2-server#getclient-clientid-clientsecret-callback).
