### ISSUE TITLE
Bug refresh token

### ISSUE THREAD

**Issue by charleston10** [thomseddon/node-oauth2-server#217]
POST /oauth2/token
Authorization Basic  21561465165...
grant_type refresh_token
refresh_token f47be6dbb1730e6cf677147094781abac7f04bfb

Result
{
  "code": 503,
  "error": "server_error",
  "error_description": "server_error"
}

How to fix?

**Comment by charleston10** [comment]
I solve the problem debugging the lib

I was in error in the file
grant.js in method saveRefreshToken

This error 

 > message: 'OAuthRefreshTokens validation failed',
 name: 'ValidationError',
 errors:
  { userId:
     { [CastError: Cast to String failed for value "[object Object]" at path "u
erId"]

Fix changing the two methods in model oauth2.js

saveAccessToken 
```javascript
model.saveAccessToken = function (token, clientId, expires, userId, callback) {
  // *** INSERTED ***//
  if(userId.id){
    userId = userId.id;
  }
  //*****//
  
  var accessToken = new OAuthAccessTokensModel({
    accessToken: token,
    clientId: clientId,
    userId: userId,
    expires: expires
  });
  
  accessToken.save(callback)
};

```

saveRefreshToken
```javascript
model.saveRefreshToken = function (token, clientId, expires, userId, callback) {
   // *** INSERTED ***//
  if(userId.id){
    userId = userId.id;
  }
  //*****// 
  
  var refreshToken = new OAuthRefreshTokensModel({
    refreshToken: token,
    clientId: clientId,
    userId: userId,
    expires: expires
  });

  refreshToken.save(callback);
};
```

Result

POST /oauth2/token

Authorization Basic OGRlNzlmM...

grant_type refresh_token

refresh_token f47be6dbb1730e6cf677147094781abac7f04bfb

> {
  "token_type": "bearer",
  "access_token": "a7cfc067e8b1e1b8060c93215ddb5e157cdab9de",
  "expires_in": 3600,
  "refresh_token": "efa9f47c1f8626dd097b4f8497fd8ad6d7a41bee"
}

**Comment by yanqing6628780** [comment]
thank you very much.
author`s example is not update.

**Comment by charleston10** [comment]
@yanqing6628780 I forked this library and customized with fixe errors
https://www.npmjs.com/package/maestro-node-oauth

**Comment by yanqing6628780** [comment]
grant.js in function useRefreshTokenGrant 
```  
return self.user = {id: refreshToken.userId}
```   
so your saveAccessToken can not save correct userId to mongodb.
it is too bad...

**Comment by maxtruxa** [comment]
@yanqing6628780 If you found a problem with charleston10's fork, please open an issue on his repo.
