### ISSUE TITLE
Capital B for bearer

### ISSUE THREAD

**Issue by sbutalia** [thomseddon/node-oauth2-server#218]
https://github.com/thomseddon/node-oauth2-server/blob/master/lib/grant.js#L459

Could you please update to "Bearer" with a capital B
It's a standard and passportjs-oauth2 isn't working unless the token type is with a capital B.

**Comment by sbutalia** [comment]
Nevermind, Saw that you have this in 3.0.0 milestone

**Comment by evert** [comment]
I don't see this in the 3.0.0 milestone. Could this get reopened?

**Comment by mjsalinger** [comment]
@evert This change has been merged into `master`.  Planning to release 3.0.0-b3 today or tomorrow at the latest.

**Comment by evert** [comment]
Ah I saw it still in lower-case [here](https://github.com/oauthjs/node-oauth2-server/blob/master/lib/token-types/bearer-token-type.js#L35) but I assumed wrong then. Thank you!
