### ISSUE TITLE
Best Way to Retrieve ClientId

### ISSUE THREAD

**Issue by cthomaschase** [thomseddon/node-oauth2-server#220]
What is the best way to get the current authenticated clientId? Right now I'm using `req.oauth.bearerToken.clientId`

Looks like it used to be exposed as req.client, but express already uses that.

**Comment by thomseddon** [comment]
Best way would be via the `req.oauth.client` object it contains `req.oauth.client.clientId` `req.oauth.client.clientSecret`

Thanks!
