### ISSUE TITLE
What pattern to use to protect dozens routes in express app, but leave some unprotected?

### ISSUE THREAD

**Issue by eighteight** [thomseddon/node-oauth2-server#265]
I have dozens of routes in the express based app with the added complexity of multiple versions. The routes are structured in subfolders:

![screen shot 2016-03-04 at 2 41 46 pm](https://cloud.githubusercontent.com/assets/542368/13538228/53cbbe6e-e217-11e5-9f5c-bbb02a95bb7a.png)

My naive approach at this point has been to embed the oauth.authorise() call in the routes as follows (taking route1.js as example)

```
var oauth = require('../../../oauth2/oauth2server');

function find(req, res){
...
}

var router = express.Router();

router.route('/')
  .get(oauth.authorise(),find);

```
The deficiency of this approach is that every route has to be configured with the _authorise()_ call, and there are too many of them.

My desire is to embed the call, such as _oauth.authorise()_ in one place (and make it configurable, for say _dev_ and _prod_ environments) into the the router's methods across entire app, but leave some of the routes without authorisation. 

How would I do that?

Thanks.

**Comment by mjsalinger** [comment]
Is there a pattern to the authorize vs unauthorize routes?

**Comment by eighteight** [comment]
@mjsalinger No, and I am expecting the future developers of this app to want to enable different authorisation levels to their routes at will.

**Comment by mjsalinger** [comment]
One way to do it would be to create an array of the routes that you want to secure (or one that you want to leave unsecured, whichever seems more useful), and then create a middleware that executes before your routes.  

```
var routesToSecure = [
  '/api/routeA',
  '/api/routeB',
]; 

app.use(function(req, res, next) { 
  if (req.path in routesToSecure) {
    return oauth.authorize()(req, res, next);
  else {
    next()
  {
});
```

**Comment by eighteight** [comment]
@mjsalinger Michael, thanks a lot. That works!
