### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by ghost** [thomseddon/node-oauth2-server#49]
Add use scope

**Comment by mjsalinger** [comment]
Thoughts on implementation - 

* An additional (optional) callback function in authCodeGrant `validateScope`, which passes the scope from the request and returns the user-granted scope.  
* If scope is included as part of the authCodeGrant request, the results of `validateScopeScope` are saved along with the auth grant. 
* When requesting a token, scope can be validated via a model definition 'getScope' 
* The granted scope is returned in the access token response if it was included anywhere in the request chain

**Comment by lfk** [comment]
Submitted PR #149 for review.

**Comment by mjsalinger** [comment]
Scope has been implemented in the new PR #203.  Closing to clean up the issues.
